sudo: required
services:
  - docker

before_install:
  - docker build -t depas98/docker-react -f Dockerfile.dev .

script:
  - docker run depas98/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-2682431124680"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secure: "$AWS_SECRET_KEY"
